### ISSUE TITLE
help

### ISSUE THREAD

**Issue by uxks** [behindthegarage/sports-arbitrage-betting-assistant#1]
just says Error fetching sports: 401
Failed to fetch sports.
can u help

**Comment by behindthegarage** [comment]
To configure the application with your Odds API key, create a .env file in the root directory and add ODDS_API_KEY='your_api_key_here', replacing your_api_key_here with your actual API key. Save the .env file to complete the setup.

This needs to be added to the README.MD.

**Comment by uxks** [comment]
i got it to work thank you, how good is the arb accuracy
